### ISSUE TITLE
How to use reader class

### ISSUE THREAD

**Issue by ghost** [do-m-en/libarchive_cpp_wrapper#4]
It seems like the reader class is implemented as a singleton but without reference to itself.

Say we want to implement a DataLoader class that extracts a large tar file. The archive contains many large files that are too big to fit in RAM. It can iterate over all files (headers) inside the archive and it can iterate over the contents of the files line-by-line.

In my opinion this is a simple common use-case but I do not see how this can be achieved with your class. Am I missing something or is it just not supposed to be possible?

**Comment by do-m-en** [comment]
What do you mean by singleton? It's a stream/iterator/range view that iterates over files/entries contained inside an archive. Then each entry is read as a stream so at no point in time is the whole file in the memory if you don't want to.

The example opens a file stream and puts it into archive reader constructor (wrapped inside make_reader convenience function that you can treat as a constructor call). Then it iterates over entries (streaming them on demand from file system, over stream, through libarchive and finally to the get_stream() function). The get_stream function returns a stream of a single entry and is a normal stream (same as C++ string stream, file stream...) so you can read it chunk by chunk but for the sake of a simpler example I just called .rdbuf() function on it to read the entire stream.

It's been years since I implemented this wrapper so it doesn't support the latest libarchive options (library has been extended in the meantime), iterator is not fully C++ compliant (doesn't use iterator traits etc) and I forgot how exactly I implemented what but this library still works exactly as you described.

Just provide your own streams (for creating entries they must support multiple access - pubseekoff, pubseekpos - but this could be changed so that entry would have an additional constructor that would also get stream size as a parameter) the rest of the constructors are single pass if I recall correctly.

I haven't tried it but reading entry line by line would be something along this lines:

```
auto stream = entry->get_stream();
for (std::string line; std::getline(stream, line); )
{
}
```

**Comment by do-m-en** [comment]
I guess it's time to look at the library and face lift it a bit after all these years.

I hope I answered your questions but the annoying part of being the author is that the examples on the first page seem self explanatory and simple for me...

If I haven't answered it could you please provide me with a pseudo code of what you are trying to achieve and I'll try to write a functional example (although I'm quite certain that the only thing that needs to be changed in the example is the replacement of .rdbuf() with the std::getline).

Also could you explain why you think that reader class is a singleton (it's not but I'm trying to understand better where the confusion came from so that I can perhaps simplify it)?

**Comment by ghost** [comment]
Hi
First of all thanks for the reply, I actually didn't expect you to respond since there hasn't been any activity on the project for some years.
Secondly I didn't mean any offense and very much appreciate the work you put into this code, it has helped me a lot.

The term singleton is inaccurate but I have never seen a class structured like this one before (I also don't have that much experience with C++). It is maybe more like a class that is a factory of itself, if that makes any sense.
What I am trying to achieve is to read a tar.bz2 file containing a number of sub directories each with two files like so:
```
archive.tar.bz2
    - dir_1
        - file_1.a
        - file_1.b
    - dir_2
        - file_2.a
        - file_2.b
    - ...
```
I am trying to search through the archive and only read the contents of file_x.a and file_x.b. Both files contain timeseries data that have been logged in parallel and I intent to replay the data (timestamped lines/strings). The problem is that file_x.b does not fit in RAM so it can only be streamed from disk. But file_x.a and file_b.x must be streamed "at the same time" in order to recreate the scene of when the data was logged. 
So what I really want to do is read file_x.a completely to RAM and then return a stream to file_x.b so that I can loop through the lines in both files at the same time. Lines of the two files will be synced using the timestamps.

Is there a way of selecting an entry in the archive by its path (e.g. dir_1/file_1.a)? 
Or does the bz1 compression prevent me from doing this without decompressing the entire archive first?

I hope you can find the time to point me in the right direction and thanks for your time!

EDIT.
Hi @do-m-en 
I found out how to collect specific entries from a compressed archive. The confusion was caused by my lack of understanding of smart pointers. It is this line in the archive_reader_iterator.hpp file that allows us to manually filter through the entries and process them after the entire archive is checked:
```
std::shared_ptr<entry> operator*();
```
Again thanks for the great work!
